apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "koencluster-637b"
spec:
  rules:
  - host: http://51.104.148.240
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "koencluster-637b"
            port:
              number: 80