on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: koenregistry.azurecr.io
        username: ${{ secrets.acr_koenregistry_username }}
        password: ${{ secrets.acr_koenregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AllDailyDuties-AuthService" -f  "AllDailyDuties-AuthService/Dockerfile" -t koenregistry.azurecr.io/koencluster:${{ github.sha }} --label dockerfile-path=AllDailyDuties-AuthService/Dockerfile
        docker push koenregistry.azurecr.io/koencluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_koencluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: koenregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_koenregistry_username }}
        container-registry-password: ${{ secrets.acr_koenregistry_password }}
        secret-name: koenclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          koenregistry.azurecr.io/koencluster:${{ github.sha }}
        imagepullsecrets: |
          koenclusterdockerauth
