on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build-and-deploy:
    runs-on: self-hosted
    needs:  build-test
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push image to registry
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AllDailyDuties-AuthService/" -f  "Dockerfile" -t http://http://192.168.240.3:32000/discountservice:latest --label dockerfile-path=Dockerfile
        docker push http://http://192.168.240.3:32000/discountservice:latest
    
    - name: Deploy to Microk8s cluster
      id: deploy
      run: |
        microk8s kubectl apply -f ./manifests/deployment.yml
        microk8s kubectl apply -f ./manifests/service.yml
